"""
Lista dei 63 giocatori reali con quotazioni.
Ruoli: POR = Portiere, CAM = Giocatore di campo (calcio a 5)
Status: I = dentro lista, O = fuori lista (almeno 1 obbligatorio in squadra)
"""

PLAYERS = [
    {"id": "p01", "nome": "Adriano De Nardez",            "ruolo": "CAM", "quotazione": 6.0,  "squadra": "Ocaro",                    "status": "I"},
    {"id": "p02", "nome": "Alessandro Berardito",          "ruolo": "POR", "quotazione": 11.0, "squadra": "Pantaglivicina",            "status": "I"},
    {"id": "p03", "nome": "Alessandro De Carolihno",       "ruolo": "CAM", "quotazione": 17.0, "squadra": "Ocaro",                    "status": "I"},
    {"id": "p04", "nome": "Alessandro Guarciolini",        "ruolo": "CAM", "quotazione": 15.0, "squadra": "Civitella",                "status": "O"},
    {"id": "p05", "nome": "Alessandro Orsolini",           "ruolo": "CAM", "quotazione": 5.0,  "squadra": "Civitella",                "status": "I"},
    {"id": "p06", "nome": "Alessio Ciminihno",             "ruolo": "CAM", "quotazione": 15.0, "squadra": "Boca Pilone",              "status": "I"},
    {"id": "p07", "nome": "Alessio Lilloski",              "ruolo": "CAM", "quotazione": 15.0, "squadra": "Ocaro",                    "status": "I"},
    {"id": "p08", "nome": "Alex De Vellonis",              "ruolo": "CAM", "quotazione": 15.0, "squadra": "Vallebona",                "status": "I"},
    {"id": "p09", "nome": "Andrea Carlesito",              "ruolo": "CAM", "quotazione": 11.0, "squadra": "Vallebona",                "status": "I"},
    {"id": "p10", "nome": "Andrea Di Girolamini",          "ruolo": "POR", "quotazione": 19.0, "squadra": "Il branco della canzatora","status": "O"},
    {"id": "p11", "nome": "Andrea Fortegentile",           "ruolo": "CAM", "quotazione": 20.0, "squadra": "Boca Pilone",              "status": "O"},
    {"id": "p12", "nome": "Angelo Continez",               "ruolo": "CAM", "quotazione": 3.0,  "squadra": "Ocaro",                    "status": "I"},
    {"id": "p13", "nome": "Antonio De Stefanovic",         "ruolo": "CAM", "quotazione": 12.0, "squadra": "Vallebona",                "status": "I"},
    {"id": "p14", "nome": "Carmelo Vicanoli",              "ruolo": "CAM", "quotazione": 16.0, "squadra": "Civitella",                "status": "I"},
    {"id": "p15", "nome": "Cesare De Carolihno",           "ruolo": "CAM", "quotazione": 13.0, "squadra": "Pantaglivicina",           "status": "I"},
    {"id": "p16", "nome": "Christian Fraboom",             "ruolo": "CAM", "quotazione": 2.0,  "squadra": "Ocaro",                    "status": "I"},
    {"id": "p17", "nome": "Christian Mattarellinez",       "ruolo": "CAM", "quotazione": 19.0, "squadra": "Boca Pilone",              "status": "I"},
    {"id": "p18", "nome": "Claudio Palombani",             "ruolo": "CAM", "quotazione": 12.0, "squadra": "Civitella",                "status": "I"},
    {"id": "p19", "nome": "Cristian De Nardez",            "ruolo": "CAM", "quotazione": 2.0,  "squadra": "Ocaro",                    "status": "I"},
    {"id": "p20", "nome": "Cristian Pancioni",             "ruolo": "POR", "quotazione": 10.0, "squadra": "Civitella",                "status": "I"},
    {"id": "p21", "nome": "Daniele De Sanctis",            "ruolo": "CAM", "quotazione": 8.0,  "squadra": "Pantaglivicina",           "status": "I"},
    {"id": "p22", "nome": "Daniele Falcoz",                "ruolo": "CAM", "quotazione": 12.0, "squadra": "Il branco della canzatora","status": "I"},
    {"id": "p23", "nome": "Daniele Fraboom",               "ruolo": "CAM", "quotazione": 20.0, "squadra": "Il branco della canzatora","status": "I"},
    {"id": "p24", "nome": "Daniele Marchettini",           "ruolo": "CAM", "quotazione": 2.0,  "squadra": "Boca Pilone",              "status": "I"},
    {"id": "p25", "nome": "Davide Nirchiez",               "ruolo": "CAM", "quotazione": 12.0, "squadra": "Civitella",                "status": "I"},
    {"id": "p26", "nome": "Davide White",                  "ruolo": "CAM", "quotazione": 7.0,  "squadra": "Pantaglivicina",           "status": "I"},
    {"id": "p27", "nome": "Elio Ciminihno",                "ruolo": "CAM", "quotazione": 12.0, "squadra": "Boca Pilone",              "status": "I"},
    {"id": "p28", "nome": "Emanuele Berardini",            "ruolo": "CAM", "quotazione": 10.0, "squadra": "Ocaro",                    "status": "I"},
    {"id": "p29", "nome": "Emanuele Margiottini",          "ruolo": "CAM", "quotazione": 6.0,  "squadra": "Boca Pilone",              "status": "I"},
    {"id": "p30", "nome": "Filippo Continez",              "ruolo": "CAM", "quotazione": 18.0, "squadra": "Ocaro",                    "status": "I"},
    {"id": "p31", "nome": "Francesco Bread",               "ruolo": "CAM", "quotazione": 18.0, "squadra": "Vallebona",                "status": "O"},
    {"id": "p32", "nome": "Francesco Continez",            "ruolo": "POR", "quotazione": 15.0, "squadra": "Boca Pilone",              "status": "I"},
    {"id": "p33", "nome": "Francesco Giulianovic",         "ruolo": "CAM", "quotazione": 7.0,  "squadra": "Vallebona",                "status": "I"},
    {"id": "p34", "nome": "Francesco Palombini",           "ruolo": "CAM", "quotazione": 1.0,  "squadra": "Pantaglivicina",           "status": "I"},
    {"id": "p35", "nome": "Francesco Red",                 "ruolo": "CAM", "quotazione": 8.0,  "squadra": "Vallebona",                "status": "I"},
    {"id": "p36", "nome": "Gabriele Red",                  "ruolo": "CAM", "quotazione": 8.0,  "squadra": "Pantaglivicina",           "status": "I"},
    {"id": "p37", "nome": "Gianlorenzo Porrettas",         "ruolo": "CAM", "quotazione": 7.0,  "squadra": "Vallebona",                "status": "I"},
    {"id": "p38", "nome": "Gianmarco Pavianovic",          "ruolo": "CAM", "quotazione": 13.0, "squadra": "Vallebona",                "status": "I"},
    {"id": "p39", "nome": "Giorgio Foschito",              "ruolo": "CAM", "quotazione": 6.0,  "squadra": "Il branco della canzatora","status": "I"},
    {"id": "p40", "nome": "Giuseppe Vicanos",              "ruolo": "CAM", "quotazione": 10.0, "squadra": "Il branco della canzatora","status": "I"},
    {"id": "p41", "nome": "Ivan Ferrantez",                "ruolo": "CAM", "quotazione": 14.0, "squadra": "Pantaglivicina",           "status": "I"},
    {"id": "p42", "nome": "Lamberto Appeticchiez",         "ruolo": "CAM", "quotazione": 4.0,  "squadra": "Boca Pilone",              "status": "I"},
    {"id": "p43", "nome": "Livio Ruota",                   "ruolo": "CAM", "quotazione": 2.0,  "squadra": "Boca Pilone",              "status": "I"},
    {"id": "p44", "nome": "Luca Lattanzini",               "ruolo": "CAM", "quotazione": 8.0,  "squadra": "Civitella",                "status": "I"},
    {"id": "p45", "nome": "Luca Palmeiras",                "ruolo": "POR", "quotazione": 20.0, "squadra": "Ocaro",                    "status": "O"},
    {"id": "p46", "nome": "Luca Recinez",                  "ruolo": "CAM", "quotazione": 10.0, "squadra": "Vallebona",                "status": "I"},
    {"id": "p47", "nome": "Manuel Perskilli",              "ruolo": "CAM", "quotazione": 9.0,  "squadra": "Ocaro",                    "status": "I"},
    {"id": "p48", "nome": "Marco Palumbo",                 "ruolo": "CAM", "quotazione": 1.0,  "squadra": "Civitella",                "status": "I"},
    {"id": "p49", "nome": "Marco Riccio",                  "ruolo": "CAM", "quotazione": 14.0, "squadra": "Boca Pilone",              "status": "I"},
    {"id": "p50", "nome": "Marco Totini",                  "ruolo": "CAM", "quotazione": 2.0,  "squadra": "Il branco della canzatora","status": "I"},
    {"id": "p51", "nome": "Matteo Baldassarre Giuffridez", "ruolo": "CAM", "quotazione": 6.0,  "squadra": "Il branco della canzatora","status": "I"},
    {"id": "p52", "nome": "Nicolas Orsolini",              "ruolo": "CAM", "quotazione": 5.0,  "squadra": "Civitella",                "status": "I"},
    {"id": "p53", "nome": "Riccardo Mattons",              "ruolo": "CAM", "quotazione": 19.0, "squadra": "Pantaglivicina",           "status": "O"},
    {"id": "p54", "nome": "Roberto Carlesito",             "ruolo": "POR", "quotazione": 15.0, "squadra": "Vallebona",                "status": "I"},
    {"id": "p55", "nome": "Samuele Perskilli",             "ruolo": "CAM", "quotazione": 9.0,  "squadra": "Ocaro",                    "status": "I"},
    {"id": "p56", "nome": "Samuele Radicihno",             "ruolo": "CAM", "quotazione": 9.0,  "squadra": "Pantaglivicina",           "status": "I"},
    {"id": "p57", "nome": "Simone De Carolihno",           "ruolo": "CAM", "quotazione": 10.0, "squadra": "Pantaglivicina",           "status": "I"},
    {"id": "p58", "nome": "Simone Pancioni",               "ruolo": "CAM", "quotazione": 14.0, "squadra": "Boca Pilone",              "status": "I"},
    {"id": "p59", "nome": "Simone Zaccinihno",             "ruolo": "CAM", "quotazione": 3.0,  "squadra": "Boca Pilone",              "status": "I"},
    {"id": "p60", "nome": "Stefano Fraboom",               "ruolo": "CAM", "quotazione": 15.0, "squadra": "Il branco della canzatora","status": "I"},
    {"id": "p61", "nome": "Stefano Totini",                "ruolo": "CAM", "quotazione": 9.0,  "squadra": "Il branco della canzatora","status": "I"},
    {"id": "p62", "nome": "Valerio Berardihno",            "ruolo": "CAM", "quotazione": 2.0,  "squadra": "Civitella",                "status": "I"},
    {"id": "p63", "nome": "Valerio Rome",                  "ruolo": "CAM", "quotazione": 18.0, "squadra": "Il branco della canzatora","status": "I"},
]

assert len(PLAYERS) == 63, f"Ci sono {len(PLAYERS)} giocatori, ne servono 63!"
